project:
  type: website

website:
  title: "John Mphande"
  description: "This Is John Mphande personal blog insights"
  navbar:
    right:
      - text: Blogs
        href: blog.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/cowden-john-mphande-5a4a081b0/
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://www.github.com/MphandeJohn
      - text: Archive
        href: archive.qmd
format:
  html:
    theme: journal
    css: styles.css

editor: visual

